# .github/workflows/playwright-e2e.yml
name: Playwright E2E Tests

on:
  # Listen for deployment status events, specifically from Netlify
  deployment_status:

jobs:
  e2e_tests:
    # Only run this job if the deployment status is 'success'
    # and the environment is a Netlify preview deployment
    # if: github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.target_url, 'netlify.app') && github.event.deployment.environment == 'Preview'
    runs-on: ubuntu-latest
    timeout-minutes: 15 # Adjust as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Checkout the specific commit that triggered the deployment
          ref: ${{ github.event.deployment.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your Node.js version

      - name: Install dependencies
        run: npm ci # Or yarn install, pnpm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          # The target_url from the deployment_status event is the deploy preview URL
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          # Add any other necessary environment variables for your tests
          # EXAMPLE_API_KEY: ${{ secrets.EXAMPLE_API_KEY_PREVIEW }}
        run: npx playwright test

      - name: Upload Playwright report (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/ # Or wherever your report is generated
          retention-days: 7